# .bashrc

# Source global definitions
if [ -f /etc/bashrc ]; then
	. /etc/bashrc
fi

# User specific environment
if ! [[ "$PATH" =~ "$HOME/.local/bin:$HOME/bin:" ]]
then
    PATH="$HOME/.local/bin:$HOME/bin:$PATH"
fi
export PATH

# Uncomment the following line if you don't like systemctl's auto-paging feature:
# export SYSTEMD_PAGER=

# User specific aliases and functions

echo
echo "RUNNING POSTGRES INSTANCES: `ps -ef | grep postgres.*[-]D | wc -l`"
ps -ef | grep postgres.*[-]D
echo
echo "LISTENING NETWORK PROCESSES: `netstat -anp -Ainet -A inet6 | grep LISTEN | grep -v tcp6 | wc -l`"
netstat -anp -Ainet -A inet6 | grep LISTEN | grep -v tcp6
echo
