####################################################################################################
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.metadata.name }}
spec:
  selector:
    app: {{ .Values.deployment.metadata.name }}
  type: {{ .Values.service.spec.type }}
  ports:
    - protocol: TCP
      port: {{ .Values.service.spec.ports.port }}
      targetPort: {{ .Values.service.spec.ports.targetport }}
####################################################################################################
